# Generated by Django 5.0.4 on 2024-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Клиенты'},
        ),
    ]
