# Generated by Django 5.0.4 on 2024-05-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
