# Generated by Django 5.0.4 on 2024-06-28 10:29

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='FIO',
            field=models.CharField(max_length=60, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=9, unique=True, validators=[client.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
