# Generated by Django 5.0.4 on 2024-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_client_alter_product_imei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
