# Generated by Django 5.0.4 on 2024-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Шт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imei',
            field=models.CharField(max_length=100, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.FloatField(verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on_sale', 'on_sale'), ('sold', 'sold')], default='on_sale', max_length=20, verbose_name='Статус'),
        ),
    ]
