# Generated by Django 5.0.4 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_count_alter_product_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Шт'),
        ),
    ]
