# Generated by Django 5.0.4 on 2024-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imei',
            field=models.CharField(max_length=100, unique=True, verbose_name='IMEI'),
        ),
    ]
