# Generated by Django 5.0.4 on 2024-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Затраты'},
        ),
    ]
