# Generated by Django 5.0.4 on 2024-06-28 10:29

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_expense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(validators=[dashboard.models.positive_validator], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(max_length=150, verbose_name='Тип'),
        ),
    ]
