# Generated by Django 5.0.4 on 2024-06-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_creditbase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='credit_base',
        ),
        migrations.AlterField(
            model_name='sale',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SaleCreditBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('credit_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_bases', to='sale.creditbase')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_credit_bases', to='sale.sale')),
            ],
            options={
                'verbose_name_plural': 'Продажи Рассрочка Базы',
            },
        ),
    ]
