# Generated by Django 5.0.4 on 2024-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
        ('sale', '0003_remove_sale_credit_base_alter_sale_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(related_name='product_sales', to='product.product'),
        ),
    ]
