# Generated by Django 5.0.4 on 2024-07-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_alter_sale_sold_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credit_base',
            field=models.ManyToManyField(blank=True, null=True, related_name='credit_bases', to='sale.creditbase', verbose_name='Рассрочка Бази'),
        ),
    ]
