# Generated by Django 5.0.4 on 2024-07-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_sale_discount_alter_sale_credit_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='credit_base',
            field=models.ManyToManyField(blank=True, related_name='credit_bases', to='sale.creditbase', verbose_name='Рассрочка Бази'),
        ),
    ]
