# Generated by Django 5.0.4 on 2024-06-17 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuserpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_fields', to=settings.AUTH_USER_MODEL),
        ),
    ]
