# Generated by Django 5.0.4 on 2024-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuserpermission_credit_base_can_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserpermission',
            name='sale_can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
