# Generated by Django 5.0.4 on 2024-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuserpermission_sale_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserpermission',
            name='client_can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuserpermission',
            name='product_can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
